apiVersion: 'solution.sap/v1'
kind: Solution

metadata:
  name: agent-solution
  description: Simple agent solution for integration testing
  version: "1.0.0"

type: composite

assets:
  - ref: ./assets/agent/asset.yaml
